# .github/workflows/python-tests.yml
name: Python Tests

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger the workflow on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Specify Python versions to test against

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest  # Run all tests with pytest
