# .github/workflows/python-tests.yml
name: Python Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]  # Specify Python versions to test against

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install dependencies for Firefox
          sudo apt-get update
          sudo apt-get install -y firefox-geckodriver

      - name: Run tests
        run: |
          pytest  # Run all tests with pytest
